[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.poetry]
name = "keras-matmulless"
version = "0.0.1.dev1"
description = "Keras layers without using matrix multiplications."
license = "MIT"
authors = ["PhotonicGluon <25820201+PhotonicGluon@users.noreply.github.com>"]
readme = "README.md"
keywords = []
classifiers = []

[[tool.poetry.source]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[tool.poetry.dependencies]
python = "^3.9"
keras = "~3.3.3"

[tool.poetry.group.backends.dependencies]
jax = "<0.4.29"
tensorflow = "~2.16.1"
torch = {version = "^2.3.1+cpu", source = "pytorch-cpu"}
torchvision = {version = "^0.18.1+cpu", source = "pytorch-cpu"}
torchaudio = {version = "^2.3.1+cpu", source = "pytorch-cpu"}

[tool.poetry.group.dev.dependencies]
pytest = "~8.2.2"
pytest-cov = "~5.0.0"
sphinx = "~7.3.7"
sphinx-rtd-theme = "^2.0.0"

[tool.poetry.urls]
