[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.poetry]
name = "keras-matmulless"
version = "0.0.1.dev1"
description = "Keras layers without using matrix multiplications."
license = "MIT"
authors = ["PhotonicGluon <25820201+PhotonicGluon@users.noreply.github.com>"]
readme = "README.md"
keywords = []
classifiers = []
packages = [{ include = "keras_mml" }]

[[tool.poetry.source]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[tool.poetry.dependencies]
# Main dependencies
python = "^3.9"
keras = "~3.3.3"
numpy = "~1.26.4"

# Tensorflow
tensorflow = { version = "~2.16.1", optional = true }

# PyTorch
torch = { version = "^2.3.1+cpu", source = "pytorch-cpu", optional = true }
torchvision = { version = "^0.18.1+cpu", source = "pytorch-cpu", optional = true }
torchaudio = { version = "^2.3.1+cpu", source = "pytorch-cpu", optional = true }

# Jax
jax = { version = "<0.4.29", extras = ["cpu"], optional = true }

# Notebook
jupyter = { version = "^1.0.0", optional = true }
notebook = { version = "~7.2.1", optional = true }

[tool.poetry.group.dev.dependencies]
# Tests
pytest = "~8.2.2"
pytest-cov = "~5.0.0"

# Docs
myst-parser = "~3.0.1"
sphinx = "~7.3.7"
furo = "2024.5.6"
sphinx-copybutton = "~0.5.2"
sphinx-design = "~0.6.0"
sphinx-autodoc-typehints = "~2.1.1"

[tool.poetry.extras]
# Keras backends
tensorflow = ["tensorflow"]
torch = ["torch", "torchvision", "torchaudio"]
jax = ["jax"]

# Others
notebook = ["jupyter", "notebook"]
