[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.poetry]
name = "keras-matmulless"
version = "0.0.1.dev1"
description = "Keras layers without using matrix multiplications."
license = "MIT"
authors = ["PhotonicGluon <25820201+PhotonicGluon@users.noreply.github.com>"]
readme = "README.md"
keywords = []
classifiers = []

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.dev.dependencies]

[tool.poetry.urls]
