name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
      - name: Install Project Dependencies
        run: poetry install --with dev,tensorflow,torch,jax
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          pylint: true
