name: Lint

on:
  push:
    branches:
      - main
    paths:
      - "**/*.py"
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: write
  
jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
      - name: Install Project Dependencies
        run: python install.py dev --backend tensorflow torch jax
      - name: Add PyLint Executable From Poetry Env To PATH
        run: echo "PATH=$(poetry env info --path)/bin:$PATH" >> $GITHUB_ENV
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          pylint: true
