name: Lint

on:
  push:
    branches:
      - main
    paths:
      - "**/*.py"
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: write
  
jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Run Ruff Linter
        uses: chartboost/ruff-action@v1
        with:
          version: 0.5.1
