name: Nightly Build

on:
  push:
    branches:
      - nightly

jobs:
  publish-testpypi:
    uses: ./.github/workflows/publish_to_testpypi.yml
    with:
      continue_on_error: true
    secrets: inherit
