name: Nightly Build

on:
  schedule:
  - cron: "59 23 * * *"
  workflow_dispatch:

jobs:
  run-tests:
    uses: ./.github/workflows/run_tests.yml
  publish-testpypi:
    needs: [run-tests]
    uses: ./.github/workflows/publish_to_testpypi.yml
