name: Publish Python Package To TestPyPi

on: 
  workflow_call:
    inputs:
      continue_on_error:
        type: boolean
        required: false
        default: false
      is_nightly_build:
        type: boolean
        required: false
        default: false
    secrets:
      TEST_PYPI_API_TOKEN:
        required: true

permissions:
  contents: read

jobs:
  publish-testpypi:
    name: Publish to TestPyPi
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/keras-matmulless
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
      - name: Install Building Dependencies
        run: |
          poetry self add "poetry-dynamic-versioning[plugin]"
          python install.py build
          poetry dynamic-versioning enable
      - name: Build Package
        run: POETRY_IS_NIGHTLY_BUILD=${{ inputs.is_nightly_build }} poetry build
      - name: Publish Package
        uses: pypa/gh-action-pypi-publish@67339c736fd9354cd4f8cb0b744f2b82a74b5c70
        continue-on-error: ${{ inputs.continue_on_error }}
        with:
          repository-url: https://test.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
