name: Run Tests on Pull to Release

on:
  pull_request:
    branches:
      - release

jobs:
  run-tests:
    uses: ./.github/workflows/run_tests.yml
    with:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
