name: Run Training Tests

on: 
  workflow_call:
  workflow_dispatch:

jobs:
  mnist-test:
    name: MNIST Classification Test
    uses: ./.github/workflows/run_training_test.yml
    with:
      script_name: mnist.py
  time-series-test:
    name: Time Series Forecasting Test
    uses: ./.github/workflows/run_training_test.yml
    with:
      script_name: time_series_forecasting.py
