name: Run Tests

on: 
  workflow_call:
    inputs:
      with_backend_tests:
        type: boolean
        default: true
      with_version_tests:
        type: boolean
        default: true
    secrets:
      CODECOV_TOKEN:
        required: true
  workflow_dispatch:
    inputs:
      with_backend_tests:
        type: boolean
        default: true
      with_version_tests:
        type: boolean
        default: true

jobs:
  run-backend-tests:
    runs-on: ubuntu-latest
    if: ${{ inputs.with_backend_tests }}
    strategy:
      matrix:
        backend: ["tensorflow", "torch", "jax"]
    env:
      KERAS_BACKEND: ${{ matrix.backend }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"  # This is the lowest supported version
      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
      - name: Install Tests Dependencies
        run: python install.py test --backend ${{ matrix.backend }}
      - name: Test with Pytest
        run: poetry run pytest --eager --doctest-modules --cov=keras_mml --cov-report=xml:coverage-${{ matrix.backend }}.xml
      - name: Upload Coverage Reports to Codecov
        uses: codecov/codecov-action@v5.0.7
        with:
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload Pytest Test Results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results-${{ matrix.backend }}
          path: coverage-${{ matrix.backend }}.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
  
  run-version-tests:
    runs-on: ubuntu-latest
    if: ${{ inputs.with_version_tests }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]  # Already using 3.9 above
    env:
      KERAS_BACKEND: "jax"  # This seems to run the fastest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
      - name: Install Tests Dependencies
        run: python install.py test --backend jax
      - name: Test with Pytest
        run: poetry run pytest --doctest-modules
