name: Run Training Tests

on: 
  workflow_call:
  workflow_dispatch:

jobs:
  run-training-tests:
    strategy:
      matrix:
        script_name: ["mnist.py", "time_series_forecasting.py", "gated_linear_unit.py"]
    uses: ./.github/workflows/run_training_test.yml
    with:
      script_name: ${{matrix.script_name}}
