name: Run Tests on Main

on:
  push:
    branches:
      - main
    paths:
      - "**.py"
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    uses: ./.github/workflows/run_tests.yml
    secrets: inherit
