name: Run Tests on Main

on:
  push:
    branches:
      - main
    paths:
      - "**.py"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        backend: ["tensorflow", "torch", "jax"]
    env:
      KERAS_BACKEND: ${{ matrix.backend }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
      - name: Install Project Dependencies
        run: poetry install --with dev --extras ${{ matrix.backend }}
      - name: Test with Pytest
        run: poetry run pytest --doctest-modules --junitxml=junit/test-results-${{ matrix.backend }}-${{ matrix.python-version }}.xml --cov=keras_mml
      - name: Upload Pytest Test Results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results-${{ matrix.backend }}-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.backend }}-${{ matrix.python-version }}.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
