name: Stable Build

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  # Phase 1 - Run tests
  run-tests:
    uses: ./.github/workflows/run_tests.yml
    secrets: inherit
  # Phase 2 - Push to testing endpoint
  publish-testpypi:
    needs: [run-tests]
    uses: ./.github/workflows/publish_to_testpypi.yml
    with:
      continue_on_error: true
      is_nightly_build: true
    secrets: inherit
  # Phase 3 - Update branches
  push-to-nightly:
    needs: [publish-testpypi]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to Nightly Branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          git checkout nightly
          git merge origin/main
          git push -u origin nightly
  push-to-stable:
    needs: [publish-testpypi]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to Stable Branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          git checkout stable
          git merge origin/main
          git push -u origin stable
  # Phase 4 - Publish to PyPi
  publish-pypi:
    needs: [push-to-nightly, push-to-stable]
    uses: ./.github/workflows/publish_to_pypi.yml
    with:
      continue_on_error: true
    secrets: inherit
